# -*- coding: utf-8 -*-
"""aula4.2_questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
numero = int(input("Digite um número: "))


soma = 0
#processamento

for i in range(1, numero + 1):
    soma += i

# saida
print(f"A soma dos números de 1 a {numero} é {soma}")