# -*- coding: utf-8 -*-
"""aula4.2_questao 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
produto_positivos = 1

# Loop para ler os valores até que o usuário digite 0
while True:
    valor = int(input())  # Leitura do valor

    if valor == 0:
        break  # Encerra o loop quando o valor digitado for 0

    if valor > 0:
        produto_positivos *= valor  # Multiplica pelo produto dos positivos

# saida
print(f"Produto: {produto_positivos}")