# -*- coding: utf-8 -*-
"""aula4.2_questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# Utilizando o comando for para imprimir números de 10 a 1 em ordem decrescente
for num in range(10, 0, -1):
    print(num)