# -*- coding: utf-8 -*-
"""aula4.2_questao5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# Leitura dos valores de N e M
N = int(input())
M = int(input())


header = " "
for col in range(1, M + 1):
    header += f"{col} "
header = header.strip()

# Impressão das colunas
print(header)

#  linhas do campo de batalha naval
for linha in range(1, N + 1):
    linha_str = f"{linha}"  # Começa a linha com o número da linha
    for col in range(M):
        linha_str += " /"  # Adiciona as posições jogáveis
    print(linha_str)