# -*- coding: utf-8 -*-
"""aula4.2_questao 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
maior_valor = float('-inf')
menor_valor = float('inf')


while True:
    valor = int(input())  # Leitura do valor

    if valor == 0:
        break

    # Atualiza o maior e o menor valor encontrados
    if valor > maior_valor:
        maior_valor = valor
    if valor < menor_valor:
        menor_valor = valor

# saida
print(f"Maior: {maior_valor}")
print(f"Menor: {menor_valor}")