# -*- coding: utf-8 -*-
"""Arthur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E482B_ZGdwZEao4qBCzPx7-jtElVn9Zm
"""

from datetime import datetime
import pytz

def exibir_data_hora_brasilia():
    # Define o fuso horário de Brasília
    fuso_brasilia = pytz.timezone('America/Sao_Paulo')

    # Obtém a data e hora atuais no fuso horário de Brasília
    agora_brasilia = datetime.now(fuso_brasilia)

    # Formata a data e hora
    data_formatada = f"Data: {agora_brasilia.day:02}/{agora_brasilia.month:02}/{agora_brasilia.year}"
    hora_formatada = f"Hora: {agora_brasilia.hour:02}:{agora_brasilia.minute:02}"

    # Exibe a data e hora formatadas
    print(data_formatada)
    print(hora_formatada)

# Chama a função
exibir_data_hora_brasilia()