# -*- coding: utf-8 -*-
"""Arthur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E482B_ZGdwZEao4qBCzPx7-jtElVn9Zm
"""

import random

def adivinhar_numero():
    # Gere um numero
    numero_aleatorio = random.randint(1, 10)

    while True:
        # Solicite palpite
        palpite = int(input("Adivinhe o número entre 1 e 10: "))

        # Verifica o palpite
        if palpite > numero_aleatorio:
            print("Muito alto, tente novamente!")
        elif palpite < numero_aleatorio:
            print("Muito baixo, tente novamente!")
        else:
            print(f"Correto! O número é {numero_aleatorio}.")
            break

# Chama a função
adivinhar_numero()