# -*- coding: utf-8 -*-
"""Arthur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E482B_ZGdwZEao4qBCzPx7-jtElVn9Zm
"""

import random
import math

def calcular_raiz_soma_aleatorios():
    # Entrada valor do usuario
    n = int(input("Digite a quantidade de valores aleatórios: "))

    # Gerar numero entre 0 e 100
    valores_aleatorios = [random.randint(0, 100) for _ in range(n)]

    # Soma
    soma_valores = sum(valores_aleatorios)

    # Calcule a Raiz
    raiz_quadrada = math.sqrt(soma_valores)

    # Resultado
    print(f"A raiz quadrada da soma dos valores é: {raiz_quadrada:.2f}")

# Chama a função
calcular_raiz_soma_aleatorios()