# -*- coding: utf-8 -*-
"""Arthur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E482B_ZGdwZEao4qBCzPx7-jtElVn9Zm
"""

import emoji

def emojizar_frase():
    # Lista de emojis disponíveis
    emojis_disponiveis = {
        "❤️": ":red_heart:",
        "👍": ":thumbs_up:",
        "🤔": ":thinking_face:",
        "🥳": ":partying_face:"
    }

    # Exibe os emojis disponíveis
    print("Emojis disponíveis:")
    for texto, codigo in emojis_disponiveis.items():
        print(f"{texto} - {codigo}")

    # Solicita uma frase codificada ao usuário
    frase_codificada = input("Digite uma frase e ela será emojizada:\n")

    # Emojiza a frase
    frase_emojizada = emoji.emojize(frase_codificada, use_aliases=True)

    # Exibe a frase emojizada
    print(f"Frase emojizada:\n{frase_emojizada}")

# Chama a função
emojizar_frase()