# -*- coding: utf-8 -*-
"""aula2_questao 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

import re

def eh_palindromo(frase):
    # Remover espaços em branco e sinais de pontuação
    frase = re.sub(r'[^\w]', '', frase.lower())

    # Verificar se a frase é um palíndromo
    return frase == frase[::-1]

while True:
    entrada = input('Digite uma frase (digite "fim" para encerrar): ')

    if entrada.lower() == 'fim':
        break

    if eh_palindromo(entrada):
        print(f'"{entrada}" é palíndromo')
    else:
        print(f'"{entrada}" não é palíndromo')