# -*- coding: utf-8 -*-
"""aula2_questao 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

import random

def embaralhar_palavras(frase):
    # Separar a frase em palavras
    palavras = frase.split()
    resultado = []

    for palavra in palavras:
        if len(palavra) > 2:
            # Embaralhar as letras internas da palavra
            primeira_letra = palavra[0]
            ultima_letra = palavra[-1]
            letras_intermediarias = list(palavra[1:-1])
            random.shuffle(letras_intermediarias)
            palavra_embaralhada = primeira_letra + ''.join(letras_intermediarias) + ultima_letra
            resultado.append(palavra_embaralhada)
        else:
            resultado.append(palavra)

    # Juntar as palavras modificadas de volta em uma frase
    return ' '.join(resultado)

# Solicitar frase ao usuário
frase = input("Digite uma frase para embaralhar as palavras: ")

# Chamar a função para embaralhar as palavras da frase
resultado = embaralhar_palavras(frase)
print(resultado)