# -*- coding: utf-8 -*-
"""aula2_questao 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

def substituir_vogais_por_asterisco(frase):
    # Lista de vogais em minúsculas e maiúsculas
    vogais = 'aeiouAEIOU'

    # Inicializar a frase modificada como uma lista de caracteres
    frase_modificada = list(frase)

    # Percorrer cada caractere da frase
    for i, char in enumerate(frase_modificada):
        # Verificar se o caractere é uma vogal
        if char in vogais:
            # Substituir a vogal por "*"
            frase_modificada[i] = '*'

    # Juntar a lista de caracteres de volta em uma string
    frase_modificada = ''.join(frase_modificada)

    return frase_modificada

# Solicitar frase ao usuário
frase_original = input("Digite uma frase: ")

# Chamar a função para substituir vogais por asterisco
frase_modificada = substituir_vogais_por_asterisco(frase_original)

# Imprimir a frase modificada
print(f"Frase modificada: {frase_modificada}")