# -*- coding: utf-8 -*-
"""aula4_questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
distancia = float(input("Digite a distância da entrega em quilômetros: "))
peso = float(input("Digite o peso do pacote em quilogramas: "))

# processamento
if distancia <= 100:
    valor_frete = peso * 1
elif distancia <= 300:
    valor_frete = peso * 1.5
else:
    valor_frete = peso * 2

if peso > 10:
    valor_frete += 10

# Imprime o valor total do frete
print(f"O valor do frete é R${valor_frete:.2f}")