# -*- coding: utf-8 -*-
"""aula1_questao 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
frase = input("Digite uma frase: ")

#  lista para armazenar os indices das vogais
indices_vogais = []

# contador para contar as vogais
cont_vogais = 0

# Define as vogais em minúsculas e maiúsculas
vogais = "aeiouAEIOU"

# Itera sobre cada caractere na frase e verifica se é uma vogal
for indice, caractere in enumerate(frase):
    if caractere in vogais:
        cont_vogais += 1
        indices_vogais.append(indice)

# saida
print(f"{cont_vogais} vogais")
print(f"Índices {indices_vogais}")