# -*- coding: utf-8 -*-
"""aula1_questao 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

import random

def encrypt(nomes):
    # Gerar um valor aleatório entre 1 e 10 para a chave de criptografia
    chave_aleatoria = random.randint(1, 10)

    nomes_cript = []

    for nome in nomes:
        nome_criptografado = ''
        for caractere in nome:
            if 33 <= ord(caractere) <= 126:  # Verifica se o caractere está no intervalo visível
                novo_caractere = chr(ord(caractere) + chave_aleatoria)
                nome_criptografado += novo_caractere
            else:
                nome_criptografado += caractere

        nomes_cript.append(nome_criptografado)

    return nomes_cript, chave_aleatoria

# Exemplo de uso da função
nomes = ["Luana", "Ju", "Davi", "Vivi", "Pri", "Luiz"]
nomes_criptografados, chave = encrypt(nomes)

print("Chave de criptografia:", chave)
print("Nomes criptografados:", nomes_criptografados)