# -*- coding: utf-8 -*-
"""aula1_questao 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# Solicita ao usuário que digite seu primeiro nome e sobrenome
primeiro_nome = input("Digite seu primeiro nome: ")
sobrenome = input("Digite seu sobrenome: ")

# Concatena as strings para formar a mensagem de boas-vindas
mensagem = f"Bem-vindo(a), {primeiro_nome} {sobrenome}!"

# Imprime a mensagem de boas-vindas
print(mensagem)