# -*- coding: utf-8 -*-
"""aula1_questao 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# Solicita ao usuário que digite seu nome
nome = input("Digite seu nome: ")

# saida
for i in range(1, len(nome) + 1):
    print(nome[:i])