# -*- coding: utf-8 -*-
"""aula2_questao5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
genero = input("Informe seu gênero (M para masculino, F para feminino): ")
idade = int(input("Informe sua idade: "))
tempo_de_servico = int(input("Informe seu tempo de serviço (em anos): "))

# saida
if (genero == "F" and (idade > 60 or tempo_de_servico >= 30 or (idade >= 60 and tempo_de_servico >= 25))) or \
   (genero == "M" and (idade > 65 or tempo_de_servico >= 30 or (idade >= 65 and tempo_de_servico >= 25))):
    print(True)
else:
    print(False)