# -*- coding: utf-8 -*-
"""aula2_questao3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
idade = int(input("Digite sua idade: "))


jogou_tres_jogos = input("Já jogou pelo menos 3 jogos de tabuleiro? (True/False): ").strip().capitalize()


vitorias = int(input("Quantos jogos já venceu? "))


jogou_tres_jogos = jogou_tres_jogos == 'True'

#processamento
apto_para_ingressar = (16 <= idade <= 18) and jogou_tres_jogos and (vitorias >= 1)

# saida
if apto_para_ingressar:
    print(f"Apto para ingressar no clube de jogos de tabuleiro: {apto_para_ingressar}")
else:
    print(f"Apto para ingressar no clube de jogos de tabuleiro: {apto_para_ingressar}")
    print("Você não atende a todos os criterios para ingressar no clube de jogos de tabuleiro.")