# -*- coding: utf-8 -*-
"""aula2_questao4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KVQxZ5Im-hP1zM04LaK1GAWoLwW4JPZ
"""

# entrada
classe = input("Escolha a classe (guerreiro, mago ou arqueiro): ").strip().lower()


forca = int(input("Digite os pontos de força (de 1 a 20): "))


magia = int(input("Digite os pontos de magia (de 1 a 20): "))


pontos_consistentes = False

#processando
if classe == "guerreiro":
    pontos_consistentes = forca >= 15 and magia <= 10
elif classe == "mago":
    pontos_consistentes = forca <= 10 and magia >= 15
elif classe == "arqueiro":
    pontos_consistentes = 5 < forca <= 15 and 5 < magia <= 15

# saindo
print(f"Pontos de atributo consistentes com a classe escolhida: {pontos_consistentes}")