# -*- coding: utf-8 -*-
"""Aula5_Questão3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def ordena_por_comprimento(lista_strings):
    """
    Ordena uma lista de strings com base no comprimento das strings.

    Parâmetros:
    lista_strings (list): Lista de strings a ser ordenada.

    Retorna:
    list: Lista ordenada pelo comprimento das strings, do menor para o maior.
    """
    return sorted(lista_strings, key=lambda s: len(s))

nomes = ["Joao", "Maria", "Jose", "Gabriela", "Sol", "Luna", "Bento", "Enzo", "Fernanda"]

nomes_ordenados = ordena_por_comprimento(nomes)

print(nomes_ordenados)