# -*- coding: utf-8 -*-
"""Aula3_Questão2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def solicitar_urls():
    urls = []
    while True:
        url = input("Digite uma URL (ou 'sair' para terminar): ")
        if url.lower() == 'sair':
            break
        urls.append(url)
    return urls

urls = solicitar_urls()

dominios = [url[4:-4] for url in urls if url.startswith("www.") and url.endswith(".com")]

print("Domínios:", dominios)