# -*- coding: utf-8 -*-
"""Aula5_Questão5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def pares_unicos(numeros, soma_objetivo):
    """
    Encontra todos os pares únicos de elementos na lista cuja soma seja igual a um determinado valor.

    Parâmetros:
    numeros (list): Lista de números inteiros.
    soma_objetivo (int): Valor da soma desejada para os pares.

    Retorna:
    set: Conjunto contendo todos os pares únicos cuja soma seja igual a soma_objetivo.
    """
    pares = set()
    visto = set()

    for num in numeros:
        complemento = soma_objetivo - num
        if complemento in visto:
            par = tuple(sorted((num, complemento)))
            pares.add(par)
        visto.add(num)

    return pares

numeros_str = input("Digite os números separados por espaço: ")
numeros = list(map(int, numeros_str.split()))

soma_objetivo = int(input("Digite o valor da soma desejada: "))

resultado = pares_unicos(numeros, soma_objetivo)
print("Pares únicos cuja soma é", soma_objetivo, ":", resultado)