# -*- coding: utf-8 -*-
"""Aula5_Questão7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def avalia_tabuleiro(tabuleiro):

    for linha in tabuleiro:
        if linha[0] == linha[1] == linha[2] and linha[0] != ' ':
            print(f"Vencedor: {linha[0]}")
            return

    for coluna in range(3):
        if tabuleiro[0][coluna] == tabuleiro[1][coluna] == tabuleiro[2][coluna] and tabuleiro[0][coluna] != ' ':
            print(f"Vencedor: {tabuleiro[0][coluna]}")
            return

    if tabuleiro[0][0] == tabuleiro[1][1] == tabuleiro[2][2] and tabuleiro[0][0] != ' ':
        print(f"Vencedor: {tabuleiro[0][0]}")
        return

    if tabuleiro[0][2] == tabuleiro[1][1] == tabuleiro[2][0] and tabuleiro[0][2] != ' ':
        print(f"Vencedor: {tabuleiro[0][2]}")
        return

    print("Empate")

# Exemplo de uso:
tabuleiro1 = [
    ['X', 'O', 'X'],
    [' ', 'X', 'O'],
    ['O', ' ', 'X']
]
avalia_tabuleiro(tabuleiro1)