# -*- coding: utf-8 -*-
"""Aula2_Questão2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

import random

num_elementos = random.randint(5, 20)

elementos = [random.randint(1, 10) for _ in range(num_elementos)]

print("Lista elementos:", elementos)

soma_elementos = sum(elementos)
print("Soma dos valores da lista:", soma_elementos)

media_elementos = soma_elementos / num_elementos
print("Média dos valores da lista:", media_elementos)