# -*- coding: utf-8 -*-
"""Aula4_Questão1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

lista_original = [x for x in range(20, 51) if x % 2 == 0]

quadrados = [x ** 2 for x in lista_original]

divisiveis_por_7 = [x for x in range(1, 101) if x % 7 == 0]

paridade = ["par" if x % 2 == 0 else "ímpar" for x in range(0, 30, 3)]

print("Lista original (pares entre 20 e 50):", lista_original)
print("Quadrados da lista original:", quadrados)
print("Números entre 1 e 100 que são divisíveis por 7:", divisiveis_por_7)
print('Paridade para valores em range(0, 30, 3):', paridade)