# -*- coding: utf-8 -*-
"""Aula3_Questão3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

import random

lista = [random.randint(-10, 10) for _ in range(20)]

def encontrar_intervalo_negativos(lista):
    max_negativos = 0
    intervalo_inicio = 0
    intervalo_fim = 0

    for i in range(len(lista)):
        for j in range(i, len(lista)):
            sublista = lista[i:j+1]
            negativos = sum(1 for x in sublista if x < 0)
            if negativos > max_negativos:
                max_negativos = negativos
                intervalo_inicio = i
                intervalo_fim = j

    return intervalo_inicio, intervalo_fim

inicio, fim = encontrar_intervalo_negativos(lista)

print("Lista antes da deleção:", lista)

del lista[inicio:fim+1]

print("Lista depois da deleção:", lista)