# -*- coding: utf-8 -*-
"""Aula5_Questão6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def diferenca_entre_listas(lista1, lista2):
    """
    Encontra a diferença entre duas listas, incluindo elementos duplicados.

    Parâmetros:
    lista1 (list): Primeira lista de elementos.
    lista2 (list): Segunda lista de elementos.

    Retorna:
    list: Lista contendo elementos que estão em lista1 mas não em lista2.
    """
    set_lista1 = set(lista1)
    set_lista2 = set(lista2)

    diferenca = set_lista1 - set_lista2

    lista_diferenca = list(diferenca)

    return lista_diferenca

lista1 = input("Digite os elementos da primeira lista separados por espaço: ").split()
lista2 = input("Digite os elementos da segunda lista separados por espaço: ").split()

resultado = diferenca_entre_listas(lista1, lista2)

print("Diferença entre as listas (elementos em lista1 mas não em lista2):", resultado)