# -*- coding: utf-8 -*-
"""Aula3_Questão1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def solicitar_numeros():
    numeros = []
    while len(numeros) < 4:
        numero = int(input("Digite um número inteiro (mínimo 4 números): "))
        numeros.append(numero)
        while True:
            mais_numeros = input("Deseja adicionar mais um número? (s/n): ").lower()
            if mais_numeros == 's':
                numero = int(input("Digite um número inteiro: "))
                numeros.append(numero)
            elif mais_numeros == 'n':
                if len(numeros) >= 4:
                    return numeros
                else:
                    print("Por favor, digite pelo menos 4 números.")
            else:
                print("Resposta inválida. Digite 's' para sim ou 'n' para não.")

numeros = solicitar_numeros()

print("Lista original:", numeros)

print("Os 3 primeiros elementos:", numeros[:3])

print("Os 2 últimos elementos:", numeros[-2:])

print("Lista invertida:", numeros[::-1])

print("Elementos de índice par:", numeros[::2])

print("Elementos de índice ímpar:", numeros[1::2])