# -*- coding: utf-8 -*-
"""Aula5_Questão6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

import random

def divide_lista(lista, tamanho):
    """
    Divide uma lista em sub-listas do tamanho especificado.

    Parâmetros:
    lista (list): Lista original de elementos.
    tamanho (int): Tamanho desejado para as sub-listas.

    Retorna:
    list: Lista contendo as sub-listas divididas.
    """
    sub_listas = []
    for i in range(0, len(lista), tamanho):
        sub_listas.append(lista[i:i+tamanho])
    return sub_listas

while True:
    tamanho_lista = random.randint(5, 15)
    lista_aleatoria = [random.randint(1, 100) for _ in range(tamanho_lista)]

    print("Lista aleatória gerada:", lista_aleatoria)

    tamanho = int(input("Digite o tamanho desejado para as sub-listas (0 para sair): "))

    if tamanho == 0:
        print("Programa encerrado.")
        break

    sub_listas = divide_lista(lista_aleatoria, tamanho)

    print("Sub-listas divididas com tamanho", tamanho, ":")
    for sub_lista in sub_listas:
        print(sub_lista)
    print()