# -*- coding: utf-8 -*-
"""Aula5_Questão4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def cria_matriz(n):
    """
    Cria uma matriz nxn onde cada elemento é o produto dos índices da linha pela coluna.

    Parâmetros:
    n (int): Tamanho da matriz (número de linhas e colunas).

    Retorna:
    list: Matriz nxn preenchida conforme especificado.
    """
    matriz = []

    for i in range(n):
        linha = []
        for j in range(n):
            linha.append(i * j)
        matriz.append(linha)

    return matriz

n = int(input("Digite o tamanho da matriz (n): "))

matriz = cria_matriz(n)

for linha in matriz:
    print(linha)