# -*- coding: utf-8 -*-
"""Aula2_Questão1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

import random

lista = [random.randint(-100, 100) for _ in range(20)]

lista_ordenada = sorted(lista)
print("Lista ordenada:", lista_ordenada)

print("Lista original:", lista)

indice_maior_valor = lista.index(max(lista))
indice_menor_valor = lista.index(min(lista))
print("Índice do maior valor:", indice_maior_valor)
print("Índice do menor valor:", indice_menor_valor)