# -*- coding: utf-8 -*-
"""Aula2_Questão4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

def ler_lista(tamanho):
    lista = []
    for i in range(tamanho):
        numero = int(input(f"Digite o {i + 1}º elemento: "))
        lista.append(numero)
    return lista

def combinar_listas(lista1, lista2):
    lista_intercalada = []
    len1, len2 = len(lista1), len(lista2)
    max_len = max(len1, len2)

    for i in range(max_len):
        if i < len1:
            lista_intercalada.append(lista1[i])
        if i < len2:
            lista_intercalada.append(lista2[i])

    return lista_intercalada

tamanho1 = int(input("Digite a quantidade de elementos da lista 1: "))
print("Digite os", tamanho1, "elementos da lista 1:")
lista1 = ler_lista(tamanho1)

tamanho2 = int(input("Digite a quantidade de elementos da lista 2: "))
print("Digite os", tamanho2, "elementos da lista 2:")
lista2 = ler_lista(tamanho2)

lista_intercalada = combinar_listas(lista1, lista2)

print("Lista intercalada:", ' '.join(map(str, lista_intercalada)))