# -*- coding: utf-8 -*-
"""Aula4_Questão2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UX8SC-shQ9GZwmHkrvFmqfHcvrpm0aRQ
"""

frase = input("Digite uma frase: ")

vogais = "aeiouAEIOU"
consoantes = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"

lista_vogais = sorted([letra for letra in frase if letra in vogais])

lista_consoantes = [letra for letra in frase if letra in consoantes]

print("Lista de vogais ordenada alfabeticamente:", lista_vogais)
print("Lista de consoantes:", lista_consoantes)